### ISSUE TITLE
single location for config file

### ISSUE THREAD

**Issue by nlaurance-pyie** [pypa/bandersnatch#735]
Hi,

I installed the tool in a docker setup, I found midly confusing the fact that `runner.py` relies on a config file in `/conf/bandersnatch.conf` while the `bandersnatch` executable relies on the conf being in `/etc/bandersnatch.conf`

My view is that they should both expect it in `/etc` and both suggest a default file if it cannot be found.
So that when we log into the running container we can issue a manual `bandersnatch` command.

this is an extract of my workaround in  `docker-compose`

```
  bandersnatch:
    image: pypa/bandersnatch
    restart: always

    volumes:
      - type: bind
        source: ./bandersnatch.conf
        target: /etc/bandersnatch.conf

    command: python /bandersnatch/src/runner.py --config=/etc/bandersnatch.conf 3600

```
